
package de.tuc.in.meclab.wi3.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MarketWS", targetNamespace = "http://market.wi3.meclab.in.tuc.de/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface MarketWS {


    /**
     * 
     * @param materiallist
     * @param suppliernumber
     * @return
     *     returns boolean
     */
    @WebMethod(action = "updateRawMaterials")
    @WebResult(name = "success", partName = "success")
    @Action(input = "updateRawMaterials", output = "http://market.wi3.meclab.in.tuc.de/MarketWS/updateRawMaterialsResponse")
    public boolean updateRawMaterials(
        @WebParam(name = "suppliernumber", partName = "suppliernumber")
        String suppliernumber,
        @WebParam(name = "materiallist", partName = "materiallist")
        String materiallist);

    /**
     * 
     * @param partNumber
     * @param budget
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "getBestOffer")
    @WebResult(partName = "return")
    @Action(input = "getBestOffer", output = "http://market.wi3.meclab.in.tuc.de/MarketWS/getBestOfferResponse")
    public String getBestOffer(
        @WebParam(name = "partNumber", partName = "partNumber")
        String partNumber,
        @WebParam(name = "budget", partName = "budget")
        String budget);

}
