
package de.tuc.in.meclab.wi3.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RawMaterialsWSService", targetNamespace = "http://rawmaterialsws.wi3.meclab.in.tuc.de/", wsdlLocation = "http://localhost:8081/RawMaterialsWS?wsdl")
public class RawMaterialsWSService
    extends Service
{

    private final static URL RAWMATERIALSWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException RAWMATERIALSWSSERVICE_EXCEPTION;
    private final static QName RAWMATERIALSWSSERVICE_QNAME = new QName("http://rawmaterialsws.wi3.meclab.in.tuc.de/", "RawMaterialsWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/RawMaterialsWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RAWMATERIALSWSSERVICE_WSDL_LOCATION = url;
        RAWMATERIALSWSSERVICE_EXCEPTION = e;
    }

    public RawMaterialsWSService() {
        super(__getWsdlLocation(), RAWMATERIALSWSSERVICE_QNAME);
    }

    public RawMaterialsWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RAWMATERIALSWSSERVICE_QNAME, features);
    }

    public RawMaterialsWSService(URL wsdlLocation) {
        super(wsdlLocation, RAWMATERIALSWSSERVICE_QNAME);
    }

    public RawMaterialsWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RAWMATERIALSWSSERVICE_QNAME, features);
    }

    public RawMaterialsWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RawMaterialsWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RawMaterialsWS
     */
    @WebEndpoint(name = "RawMaterialsWSPort")
    public RawMaterialsWS getRawMaterialsWSPort() {
        return super.getPort(new QName("http://rawmaterialsws.wi3.meclab.in.tuc.de/", "RawMaterialsWSPort"), RawMaterialsWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RawMaterialsWS
     */
    @WebEndpoint(name = "RawMaterialsWSPort")
    public RawMaterialsWS getRawMaterialsWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rawmaterialsws.wi3.meclab.in.tuc.de/", "RawMaterialsWSPort"), RawMaterialsWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RAWMATERIALSWSSERVICE_EXCEPTION!= null) {
            throw RAWMATERIALSWSSERVICE_EXCEPTION;
        }
        return RAWMATERIALSWSSERVICE_WSDL_LOCATION;
    }

}
