
package de.tuc.in.meclab.wi3.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RawMaterialsWS", targetNamespace = "http://rawmaterialsws.wi3.meclab.in.tuc.de/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface RawMaterialsWS {


    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "getRawMaterials")
    @WebResult(name = "materials", partName = "materials")
    @Action(input = "getRawMaterials", output = "http://rawmaterialsws.wi3.meclab.in.tuc.de/RawMaterialsWS/getRawMaterialsResponse")
    public String getRawMaterials(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "getRandomRawMaterial")
    @WebResult(name = "material", partName = "material")
    @Action(input = "getRandomRawMaterial", output = "http://rawmaterialsws.wi3.meclab.in.tuc.de/RawMaterialsWS/getRandomRawMaterialsResponse")
    public String getRandomRawMaterials(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password);

}
